services:

  python:
    build: .
    container_name: ex2_python
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    environment:
      DB_HOST: ex2_mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: ex2_mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ex2
      MYSQL_USER: user
      MYSQL_PASSWORD: password